export const SVG_NAMESPACE = "http://www.w3.org/2000/svg";

export const SVG_TAGS = new Set([
  "svg",
  "path",
  "circle",
  "rect",
  "line",
  "polyline",
  "polygon",
  "ellipse",
  "text",
  "g",
  "defs",
  "use",
  "symbol",
  "marker",
  "clipPath",
  "mask",
  "pattern",
  "image",
  "linearGradient",
  "radialGradient",
  "stop",
  "filter",
  "feGaussianBlur",
  "tspan",
  "textPath",
  "foreignObject",
]);

export const EVENT_MAP: Record<string, string> = {
  // Mouse
  onClick: "click",
  onDblClick: "dblclick",
  onMouseDown: "mousedown",
  onMouseUp: "mouseup",
  onMouseEnter: "mouseenter",
  onMouseLeave: "mouseleave",
  onMouseMove: "mousemove",
  onMouseOver: "mouseover",
  onMouseOut: "mouseout",
  onContextMenu: "contextmenu",
  // Keyboard
  onKeyDown: "keydown",
  onKeyUp: "keyup",
  onKeyPress: "keypress",
  // Focus
  onFocus: "focus",
  onBlur: "blur",
  // Pointer
  onPointerDown: "pointerdown",
  onPointerUp: "pointerup",
  onPointerMove: "pointermove",
  onPointerEnter: "pointerenter",
  onPointerLeave: "pointerleave",
  onPointerOver: "pointerover",
  onPointerOut: "pointerout",
  onPointerCancel: "pointercancel",
  onGotPointerCapture: "gotpointercapture",
  onLostPointerCapture: "lostpointercapture",
  // Touch
  onTouchStart: "touchstart",
  onTouchEnd: "touchend",
  onTouchMove: "touchmove",
  // Drag
  onDrag: "drag",
  onDragStart: "dragstart",
  onDragEnd: "dragend",
  onDragEnter: "dragenter",
  onDragLeave: "dragleave",
  onDragOver: "dragover",
  onDrop: "drop",
  // Scroll / Wheel
  onScroll: "scroll",
  onScrollEnd: "scrollend",
  onWheel: "wheel",
  // Form
  onChange: "change",
  onInput: "input",
  onBeforeInput: "beforeinput",
  onSubmit: "submit",
  onReset: "reset",
  onSelect: "select",
  onInvalid: "invalid",
  // Clipboard
  onCopy: "copy",
  onCut: "cut",
  onPaste: "paste",
  // Composition (IME)
  onCompositionStart: "compositionstart",
  onCompositionUpdate: "compositionupdate",
  onCompositionEnd: "compositionend",
  // Resource
  onLoad: "load",
  onError: "error",
  // Animation / Transition
  onAnimationEnd: "animationend",
  onTransitionEnd: "transitionend",
  // Element-specific (details, dialog, popover)
  onToggle: "toggle",
  onBeforeToggle: "beforetoggle",
  onClose: "close",
  onCancel: "cancel",
  // Media
  onAbort: "abort",
  onCanPlay: "canplay",
  onCanPlayThrough: "canplaythrough",
  onDurationChange: "durationchange",
  onEmptied: "emptied",
  onEnded: "ended",
  onLoadedData: "loadeddata",
  onLoadedMetadata: "loadedmetadata",
  onLoadStart: "loadstart",
  onPause: "pause",
  onPlay: "play",
  onPlaying: "playing",
  onProgress: "progress",
  onRateChange: "ratechange",
  onSeeked: "seeked",
  onSeeking: "seeking",
  onStalled: "stalled",
  onSuspend: "suspend",
  onTimeUpdate: "timeupdate",
  onVolumeChange: "volumechange",
  onWaiting: "waiting",
};
