export const SVG_NAMESPACE = "http://www.w3.org/2000/svg";

export const SVG_TAGS = new Set([
  "svg",
  "path",
  "circle",
  "rect",
  "line",
  "polyline",
  "polygon",
  "ellipse",
  "text",
  "g",
  "defs",
  "use",
  "symbol",
  "marker",
  "clipPath",
  "mask",
  "pattern",
  "image",
  "linearGradient",
  "radialGradient",
  "stop",
  "filter",
  "feGaussianBlur",
  "tspan",
  "textPath",
  "foreignObject",
]);

export const EVENT_MAP: Record<string, string> = {
  onClick: "click",
  onDblClick: "dblclick",
  onChange: "change",
  onInput: "input",
  onSubmit: "submit",
  onReset: "reset",
  onKeyDown: "keydown",
  onKeyUp: "keyup",
  onKeyPress: "keypress",
  onFocus: "focus",
  onBlur: "blur",
  onMouseDown: "mousedown",
  onMouseUp: "mouseup",
  onMouseEnter: "mouseenter",
  onMouseLeave: "mouseleave",
  onMouseMove: "mousemove",
  onContextMenu: "contextmenu",
  onScroll: "scroll",
  onWheel: "wheel",
  onDragStart: "dragstart",
  onDragEnd: "dragend",
  onDragOver: "dragover",
  onDrop: "drop",
  onTouchStart: "touchstart",
  onTouchEnd: "touchend",
  onTouchMove: "touchmove",
  onAnimationEnd: "animationend",
  onTransitionEnd: "transitionend",
};

export const VALUE_PROPS = new Set(["checked", "value", "disabled", "selected", "innerHTML"]);
