packages:
  - "packages/foundation/*"
  - "packages/features/*"
  - "packages/dx/*"
  - "packages/utils/*"
  - "packages/cli/*"
  - "templates/*"
  - "playground"
  - "storybook"
  - "docs"

catalog:
  typescript: ^6.0.3
  vite: ^8.1.4
